In [8]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("BACE1 homo sapiens.csv", sep=";")

C:\Users\anuja\AppData\Local\Temp\ipykernel_32136\404889049.py:1: DtypeWarning: Columns (0: Assay Tissue ChEMBL ID, 1: Assay Tissue Name, 2: Assay Parameters) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("BACE1 homo sapiens.csv", sep=";")

In [11]:
df.head()

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL262792,NaN,NaN,1014.06,NaN,NaN,4,CC(C)[C@H](NC(=O)[C@@H](N)CCC(=O)O)C(=O)N[C@@H...,Inhibition,'=',...,CHEMBL1136466,1,Scientific Literature,Bioorg Med Chem Lett,2003,NaN,NaN,NaN,NaN,36.0
1,CHEMBL5801744,NaN,NaN,440.49,0.0,1.36,BDBM291122,CN1C(=N)N[C@@]2(CCOc3ccc(NC(=O)c4cc5ccccn5n4)c...,k_off,'=',...,CHEMBL5725782,37,BindingDB Patent Bioactivity Data,NaN,2017,NaN,NaN,NaN,NaN,NaN
2,CHEMBL4216412,NaN,NaN,415.38,0.0,3.36,18,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(C(F)...,IC50,'=',...,CHEMBL4190390,1,Scientific Literature,J Med Chem,2018,NaN,NaN,NaN,NaN,63.9
3,CHEMBL4204742,NaN,NaN,397.39,0.0,3.07,20,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(CF)O...,IC50,'=',...,CHEMBL4190390,1,Scientific Literature,J Med Chem,2018,NaN,NaN,NaN,NaN,66.6
4,CHEMBL5739936,NaN,NaN,431.47,0.0,1.12,BDBM291106,COc1ccc(C(=O)Nc2ccc3c(c2)[C@]2(CCO3)CS(=O)(=O)...,kon,'=',...,CHEMBL5725782,37,BindingDB Patent Bioactivity Data,NaN,2017,NaN,NaN,NaN,NaN,NaN

In [14]:
df.shape

(27804, 48)

In [16]:
print(df.columns.tolist())

['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase', 'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key', 'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value', 'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment', 'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate', 'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID', 'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID', 'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction', 'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation', 'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type', 'Document ChEMBL ID', 'Source ID', 'Source Description', 'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties', 'Action Type', 'Standard Text Value', 'Value']

In [17]:
type(df)

pandas.DataFrame

In [18]:
df["Standard Type"].unique()

<StringArray>
[                    'Inhibition',                          'k_off',
                           'IC50',                            'kon',
                             'Ki',                             'Kd',
                           'EC50',                            'RFU',
                     'Ratio IC50',                            'INH',
                      'k obs / 1',                          'Ratio',
                           'ED50',                       'Activity',
                           'TIME',                             'FC',
 '% Inhibition of Control Values',                       'Ratio Ki',
                             'IP',                             'Ka',
                          'pIC50',                            'Kic',
                         '% Ctrl',                           'Emax',
                           'Kcat',                             'Km',
                              'K']
Length: 27, dtype: str

In [22]:
# keep only IC50 measurements
ic50 = df[df['Standard Type'] == "IC50"].copy()

print("Number of IC50 records:", len(ic50))

Number of IC50 records: 13777

In [ ]:
ic50 = ic50[ic50["Standard Relation"] == "="]

In [25]:
ic50 = ic50[
    [
        "Molecule ChEMBL ID",
        "Smiles",
        "Standard Value",
        "Standard Units",
        "pChEMBL Value"
    ]
]

ic50.head()

,Molecule ChEMBL ID,Smiles,Standard Value,Standard Units,pChEMBL Value
2,CHEMBL4216412,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(C(F)...,63.9,nM,7.19
3,CHEMBL4204742,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(CF)O...,66.6,nM,7.18
26,CHEMBL1644466,COc1ccc(C2NC(=O)c3cc(cc(N(C)S(C)(=O)=O)c3)C(=O...,3100.0,nM,5.51
29,CHEMBL4062699,[2H]C1([2H])OC(N)=N[C@]12c1cc(-c3cc(Cl)cc(C#N)...,4.8,nM,8.32
32,CHEMBL522778,CCCCNC(=O)[C@H](C)C[C@H](O)[C@@H]1CCCCCCCCCC(=...,7600.0,nM,5.12

In [26]:
ic50 = ic50.dropna()

print(ic50.shape)

(12721, 5)

In [27]:
ic50 = ic50.drop_duplicates(subset="Smiles")

print(ic50.shape)

(8116, 5)

In [28]:
ic50.isnull().sum()

Molecule ChEMBL ID    0
Smiles                0
Standard Value        0
Standard Units        0
pChEMBL Value         0
dtype: int64

In [30]:
ic50 = ic50.dropna()
print(ic50.shape)

(8116, 5)

In [31]:
ic50[["Standard Value", "pChEMBL Value"]].head(10)

    Standard Value  pChEMBL Value
2             63.9           7.19
3             66.6           7.18
26          3100.0           5.51
29             4.8           8.32
32          7600.0           5.12
33          2500.0           5.60
36            49.0           7.31
37            16.0           7.80
41         21150.0           4.67
42          2510.0           5.60

In [32]:
ic50 = ic50.rename(columns={"pChEMBL Value": "pIC50"})

In [34]:
ic50.head()

,Molecule ChEMBL ID,Smiles,Standard Value,Standard Units,pIC50
2,CHEMBL4216412,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(C(F)...,63.9,nM,7.19
3,CHEMBL4204742,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(CF)O...,66.6,nM,7.18
26,CHEMBL1644466,COc1ccc(C2NC(=O)c3cc(cc(N(C)S(C)(=O)=O)c3)C(=O...,3100.0,nM,5.51
29,CHEMBL4062699,[2H]C1([2H])OC(N)=N[C@]12c1cc(-c3cc(Cl)cc(C#N)...,4.8,nM,8.32
32,CHEMBL522778,CCCCNC(=O)[C@H](C)C[C@H](O)[C@@H]1CCCCCCCCCC(=...,7600.0,nM,5.12

In [35]:
ic50.to_csv("bace1_clean.csv", index=False)